FROM python:3.12

RUN pip install --upgrade pip

ADD . /pyTincture/

WORKDIR /pyTincture

RUN ["pip", "install", "pytincture==0.5.2"]

WORKDIR /pyTincture/example

RUN apt-get update

EXPOSE 8070

ENTRYPOINT ["python", "py_ui.py"]
