FROM python:3.11

RUN pip install --upgrade pip

ADD . /pyTincture/

WORKDIR /pyTincture

RUN ["pip", "install", "-r", "requirements.txt"]

RUN python setup.py bdist_wheel

RUN pip install dist/pytincture-0.4.2-py3-none-any.whl

WORKDIR /pyTincture/example

RUN apt-get update

EXPOSE 8070

ENTRYPOINT ["python", "py_ui.py"]
